# In ~/.zshrc :
# 
# if [ -f ~/Workspace/ROS/config/zsh/zshrc ]; then
#     source ~/Workspace/ROS/config/zsh/zshrc
# else
#     echo "Warning: ~/Workspace/ROS/config/zsh/zshrc not found."
# fi

# Config
MY_ROS_WORKSPACE="$HOME/Workspace/ROS"

# ROS system
source /opt/ros/jade/setup.zsh
source ~/Workspace/ROS/ws/ps4_ws/devel/setup.zsh

# Aliases

# Terminator layout
alias rosterminator='terminator -l rosps4'

# Git repo
alias rosgitcd='cd $MY_ROS_WORKSPACE'

# Ros tools
alias ros_use_sim_time='rosparam set use_sim_time true'
alias ros_stereo_image_proc='rosrun stereo_image_proc stereo_image_proc __ns:=stereo'
alias ros_disparity_view='rosrun image_view disparity_view image:=/stereo/disparity'
alias ros_reconfigure='rosrun rqt_reconfigure rqt_reconfigure'

# Rosbag play   (optional arguments: -l -r 0.5)
alias rosplay_carrito1='rosbag play --clock $MY_ROS_WORKSPACE/rtab_resources/pseye_carrito/pseye_carrito1.bag $@'
alias rosplay_carrito2='rosbag play --clock $MY_ROS_WORKSPACE/rtab_resources/pseye_carrito/pseye_carrito2.bag $@'
alias rosplay_verdino='rosbag play --clock $MY_ROS_WORKSPACE/rtab_resources/pseye_verdino/2016-03-10-19-10-07.bag $@'
alias rosplay_parking='rosbag play --clock $MY_ROS_WORKSPACE/rtab_resources/stereo_parking/stereo_parking.bag $@'
alias rosplay_peatones='rosbag play --clock $MY_ROS_WORKSPACE/rtab_resources/stereo_peatones/stereo_peatones.bag $@'
alias rosplay_silla1='rosbag play --clock $MY_ROS_WORKSPACE/rtab_resources/silla/2016-05-18-18-18-05.bag $@'
alias rosplay_silla2='rosbag play --clock $MY_ROS_WORKSPACE/rtab_resources/silla/2016-05-18-18-21-11.bag $@'
alias rosplay_silla3='rosbag play --clock $MY_ROS_WORKSPACE/rtab_resources/silla/2016-05-18-18-23-42.bag $@'